# Generated by Django 6.0.6 on 2026-06-20 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Musica",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("titulo", models.CharField(db_column="TITULO", max_length=200)),
                ("artista", models.CharField(db_column="ARTISTA", max_length=200)),
                (
                    "album",
                    models.CharField(
                        blank=True, db_column="ALBUM", max_length=200, null=True
                    ),
                ),
                ("ano", models.IntegerField(blank=True, db_column="ANO", null=True)),
            ],
            options={
                "db_table": "Musicas",
                "ordering": ["titulo"],
                "managed": True,
            },
        ),
    ]
